### ISSUE TITLE
Not letting me enter "How do you help them"

### ISSUE THREAD

**Issue by sumukhshetty** [joshpitzalis/clienttree#2]
Browser: safari

<img width="983" alt="Screen Shot 2019-10-07 at 8 29 13 PM" src="https://user-images.githubusercontent.com/22879373/66323338-47e75600-e941-11e9-846a-98634c4c896f.png">

Basically when I click on How od you help them, it switchs back to who are your ideal clients.

I could not recreate it in Chrome.

**Comment by joshpitzalis** [comment]
fixed in https://github.com/joshpitzalis/clienttree/pull/18
