### ISSUE TITLE
Clicked on actually add a signature - takes me to a blank page

### ISSUE THREAD

**Issue by sumukhshetty** [joshpitzalis/clienttree#3]
After clicking on actually add a signature, it took me to a blankpage.

**Comment by sumukhshetty** [comment]
Now even when I clicked back, create a referrable email is unchecked. 

It was checked before I clicked on actually ad a signture

**Comment by joshpitzalis** [comment]
This has been fixed in v 0.0.6 https://client-tree-dev.firebaseapp.com/
